### ISSUE TITLE
improvements for v2 (or 3? what number are we on?)

### ISSUE THREAD

**Issue by aurorasmiles** [HangarMC/HangarAuth#108]
-  ~~Add indicators what fields are optional/required~~
- ~~Improve the email valid check (currently it only seems to check for *@* or something like that, so a@a works)~~
- ~~When loading the page sometimes the textboxes take a second to load which makes the page look weird/scuffed~~
- ~~Maybe check if a username/mail is already used before clicking on Sign Up?~~
- ~~Alternative: If a username/mail is already used don't reset all the fields~~
- ~~Add an indicator to the password to immediately see if it doesn't follow the requirements~~
- ~~`The password can not be used because password length must be at least 8 characters but only got 2.` sounds wrong. Suggestion: `Your password does not meet the minimum required length. It has to be at least 8 characters long, but is only 4` or something like that~~
- ~~Maybe add some requirements for the username? I'm not sure we want usernames with spaces and emojis~~

**Comment by kennytv** [comment]
Also, you shouldn't be asked to give Hangar permission to your account data, being an in-house application

**Comment by MiniDigger** [comment]
- don’t ask for access granting for hangar
- move all the optional fields (name etc) away from the initial signup page or at least have them visually distinct as optional
- better distinction between password and key usage for security (instead of just two fields above each other)
- go back to hangar/page you came from after signup? (right now signup also doesn’t actually log you into Hangar)
