### ISSUE TITLE
Login flow when using security key

### ISSUE THREAD

**Issue by aurorasmiles** [HangarMC/HangarAuth#175]
The login flow in hangar-auth feels really weird. So I click on Security Key, enter my username, and then "Sign in with security key". Then I get the `Prepare your WebAuthn device` thingy, but below that the "Password" tab is selected and I have to click on "Security Key" again, before I then get a Continue button that feels completely out of place and has the same color as Register/Forgot
1. ~~Why do I have to manually click on "Continue" after I've already clicked on "Sign in with security key"? Feels like that step is unnecessary~~ I kinda understand it now, but see the rest
2. On the second page, the "Security Key" tab should ideally be pre-selected, especially since the password-tab is empty there
3. There should be some sort of visual distinction between the Continue button and Register/Forgot. Could be a blue button as well
4. Without a text directly above the "Continue" button the spacing looks kinda weird

**Comment by MiniDigger** [comment]
passwordless signin will most likely be disabled for now

**Comment by MiniDigger** [comment]
1) is necessary cause we only load the webauthn js after you pressed the sign in with key button
2) just removed the tab
3) just rermoved the buttons
4) spacing is fixed in browsers that support :has  (https://caniuse.com/css-has)

https://github.com/HangarMC/HangarAuth/commit/9e7f617775280ffc192ba299504ef6bd358a5a02
